apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: ns-test
  labels:
    name: deployment-test
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      name: app1
      app: nginx
  template:
    metadata:
      labels:
        name: app1
        app: nginx
    spec:
      containers:
        - name: nginx-deployment
          image: nginx:1.26
