apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemonset-test
  namespace: ns-test
spec:
  selector:
    matchLabels:
      name: node-exporter
  template:
    metadata:
      labels:
        name: node-exporter
    spec:
      containers:
        - name: node-exporter
          image: prom/node-exporter


