apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: ns-test
  labels:
    app: nginx
spec:
  type: NodePort # ClusterIP Or LoadBalancer
  selector:
    app: nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
