apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: ns-test
  labels:
    name: deployment-test
spec:
  replicas: 2
  selector:
    matchLabels:
      name: app1
  template:
    metadata:
      labels:
        name: app1
    spec:
      containers:
        - name: nginx-deployment
          image: nginx:1.26
          resources:
            limits:
              cpu: "400m"
              memory: "512Mi"
            requests:
              cpu: "200m"
              memory: "128Mi"

