apiVersion: v1
kind: Pod
metadata:
  namespace: ns-test
  name: pod-tests
  labels:
    var1: var1_value
    var2: var2_value
    app.kubernetes.io/var3: var3_value
    app.kubernetes.io/var4: var4_value
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        limits:
          memory: "150Mi"
          cpu: "500m"
        requests:
          memory: "100Mi"
          cpu: "200m"
  nodeSelector:
    kubernetes.io/hostname: kuber-2
